#!/bin/bash
DOT_CONFIG_PATH=~/.config
DOT_FILES_PATH=~/dot-files

# NVIM
cp -r $DOT_CONFIG_PATH/nvim/ $DOT_FILES_PATH/.config/

# tmux
cp ~/.tmux.conf $DOT_FILES_PATH/.tmux.conf

# pylsp Configuration
cp $DOT_CONFIG_PATH/pycodestyle $DOT_FILES_PATH/pycodestyle
