#!/bin/bash
DOT_FILES_PATH=~/dot-files

# NeoVim Configuration
cp -r ~/.config/nvim/ $DOT_FILES_PATH/.config/

# tmux Configuration
cp ~/.tmux.conf $DOT_FILES_PATH/

# pylsp Configuration
cp ~/.config/pycodestyle $DOT_FILES_PATH/.config/

# gdb Configuration
cp ~/.gdbinit $DOT_FILES_PATH/
